### ISSUE TITLE
Installation : Permission denied

### ISSUE THREAD

**Issue by cyprille** [babeuloula/github-pr-review#15]
When executing `./install.sh` from the project's dir, as mentionned in the README file, the terminal returns an error from the container : 

> ./install.sh: line 22: bin/console: Permission denied

Apparently, the problem comes from the two commands at the end of the `./install.sh` file.
In fact it's just an execution permission missing on the Symfony's console file in `./bin/console`.

`chmod +x bin/console` did the trick !

**Comment by babeuloula** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [chmod +x bin/console](https://trello.com/c/46Qzkhmt/8-chmod-x-bin-console)

**Comment by babeuloula** [comment]
Fixed #17
