### ISSUE TITLE
Hostname 'github.gui' not reachable

### ISSUE THREAD

**Issue by cyprille** [babeuloula/github-pr-review#16]
Hey Babeuloula !

First of all, I'd like to thank you very much for your very cool Github GUI ;)

At the end of the installation process, I started the containers by running` ./start.sh` from `./docker` folder as mentionned in the README file.

Everything went well except that I was unable to reach the configured hostname [github.gui](url).

By looking in the docker config files, I found that the `addHost()` function in `./docker/start.sh` was not adding the hostname at all in my `/etc/hosts` file. 

So, I added it manually and then it worked immediately ;)
I think that a tiny fix for that would be cool!

**Comment by babeuloula** [comment]
The host name was `github.gui` not `gitub.gui` :stuck_out_tongue:

**Comment by cyprille** [comment]
Yes sorry, it's a typo in my issue but of course I tried github.gui so that's really an issue ;)

**Comment by babeuloula** [comment]
Did you run the scipt with a sudoer user ? For me the script works well.

**Comment by cyprille** [comment]
Yes I did :)

**Comment by cyprille** [comment]
This issue is fixed for me !
Here's how I dit it :

- I updated to the 1.0.2 version
- I removed the hostname in `/etc/hosts`
-  I launched again `./install.sh` and `./docker/start.sh`
- All working now :)

**Comment by babeuloula** [comment]
Good !
