### ISSUE TITLE
Refresh is boring

### ISSUE THREAD

**Issue by cyprille** [babeuloula/github-pr-review#23]
Hey man!

Your last release about the data refresh was pretty cool!

I'm using it and even if it's better, it's still boring to wait for the refresh loader to finish to be able to click on the PRs links...

I think you should rather refresh the data without UI blocking and then, when everything is over, you would display a refresh toast and reload the display. By this way, the UI wouldn't be stucked while refreshing and the data would be refreshed nevertheless :)

What do you think about it?

See you man!

**Comment by babeuloula** [comment]
Fix PR #26
