### ISSUE TITLE
Update babeuloula/phpcs to v1.1.0

### ISSUE THREAD

**Issue by babeuloula** [babeuloula/github-pr-review#55]
Update composer `babeuloula/phpcs` from [v1.0.1](https://github.com/babeuloula/phpcs/releases/tag/v1.0.1) to [v1.1.0](https://github.com/babeuloula/phpcs/releases/tag/v1.1.0).

**Comment by GijsGoudzwaard** [comment]
I'll pick this up

**Comment by babeuloula** [comment]
Okay. Don't forgot to add your name on README.md

**Comment by babeuloula** [comment]
Close with PR #56
